namespace Cowork.Core.Localization;

/// <summary>Bảng chuỗi tiếng Anh. Khoá phải trùng khớp <see cref="StringsVi"/>.</summary>
internal static class StringsEn
{
    internal static readonly IReadOnlyDictionary<string, string> Table =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            // ---------- Common ----------
            ["Common.Cancel"] = "Cancel",
            ["Common.Browse"] = "Browse…",
            ["Common.BrowseFolder"] = "Change folder…",
            ["Common.Scan"] = "Scan",
            ["Common.Dash"] = "—",
            ["Common.AppName"] = "Cowork",

            // ---------- Main window ----------
            ["Main.Title"] = "Cowork — daily app launcher",
            ["Main.Brand"] = "Cowork",
            ["Main.SchedulerToggle"] = "Run on schedule",
            ["Main.SchedulerToggleTip"] = "Turn the background timer that launches apps on schedule on or off",
            ["Main.Save"] = "Save",
            ["Main.SaveTip"] = "Save the app list and settings (Ctrl+S)",
            ["Main.Run"] = "▶  Run",
            ["Main.RunTip"] = "Run the selected app (F5)",
            ["Main.Stop"] = "■  Stop",
            ["Main.StopTip"] = "Stop the selected app",
            ["Main.RunAll"] = "Run all",
            ["Main.RunAllTip"] = "Launch every enabled app in order",
            ["Main.StopAll"] = "Stop all",
            ["Main.CheckSchedule"] = "Check schedule",
            ["Main.CheckScheduleTip"] = "Run one schedule check right now instead of waiting for the next tick",

            // ---------- App list ----------
            ["AppList.Title"] = "Apps",
            ["AppList.SearchTip"] = "Filter by name, group or path",
            ["AppList.Add"] = "+ Add",
            ["AppList.Duplicate"] = "Duplicate",
            ["AppList.Delete"] = "Delete",
            ["AppList.MoveUpTip"] = "Move up (affects the Run all order)",
            ["AppList.MoveDownTip"] = "Move down",
            ["AppList.NextRunPrefix"] = "Next:",
            ["AppList.DisabledTip"] = "This app is disabled and will not run",

            // ---------- Tabs ----------
            ["Tab.Overview"] = "Overview",
            ["Tab.Environment"] = "Environment",
            ["Tab.ConfigFiles"] = "Config files",
            ["Tab.Schedule"] = "Schedule",
            ["Tab.Output"] = "Output",
            ["Tab.History"] = "Run history",
            ["Tab.Settings"] = "Settings",

            // ---------- Overview ----------
            ["Overview.Empty"] = "No app selected. Click “+ Add” to create your first one.",
            ["Overview.InfoCard"] = "App details",
            ["Overview.Name"] = "App name",
            ["Overview.Group"] = "Group",
            ["Overview.GroupTip"] = "For example: Backup, Morning report, Background services",
            ["Overview.Description"] = "Description",
            ["Overview.EnabledCheck"] = "Enable this app (unchecked means it never runs, manually or on schedule)",
            ["Overview.CommandCard"] = "Command",
            ["Overview.Executable"] = "Program (.exe / .bat / .cmd / .ps1)",
            ["Overview.PickFileTip"] = "Point at one specific file",
            ["Overview.ScanFolder"] = "Scan folder…",
            ["Overview.ScanProgramTip"] = "Look for .exe/.bat/.cmd/.ps1 inside a folder",
            ["Overview.Arguments"] = "Command-line arguments",
            ["Overview.ArgumentsHint"] = "Environment variables such as %USERPROFILE% are supported. Wrap paths containing spaces in double quotes.",
            ["Overview.WorkingDir"] = "Working directory",
            ["Overview.WorkingDirHint"] = "Leave empty and Cowork uses the folder that contains the program.",
            ["Overview.RunOptionsCard"] = "Run options",
            ["Overview.SingleInstance"] = "No overlapping runs (skip while a previous instance is alive)",
            ["Overview.CaptureOutput"] = "Capture output into Cowork",
            ["Overview.RunAsAdmin"] = "Run as administrator (UAC)",
            ["Overview.RunAsAdminTip"] = "With this on, output cannot be captured",
            ["Overview.WindowStyle"] = "Window style",
            ["Overview.Timeout"] = "Auto-stop after (minutes, 0 = no limit)",
            ["Overview.StatusCard"] = "Status",
            ["Overview.StatusLabel"] = "State:",
            ["Overview.LastRunLabel"] = "Last run:",
            ["Overview.ScheduleLabel"] = "Schedule:",
            ["Overview.OpenAppFolder"] = "Open the app folder",

            // ---------- Environment ----------
            ["Env.Title"] = "App-specific environment variables",
            ["Env.Hint"] = "These apply only to the child process Cowork launches; the system is untouched. Values support %OTHER_VAR%.",
            ["Env.Add"] = "+ Add variable",
            ["Env.ColName"] = "Name",
            ["Env.ColValue"] = "Value",
            ["Env.DefaultName"] = "VAR_NAME",
            ["Env.Remove"] = "Delete",

            // ---------- Config files ----------
            ["Config.ListTitle"] = "Config files",
            ["Config.ScanTip"] = "Look for config files inside the app working directory",
            ["Config.AddManual"] = "+ Add file manually",
            ["Config.Remove"] = "Remove from list",
            ["Config.PathLabel"] = "File path",
            ["Config.PickFile"] = "Pick file…",
            ["Config.OpenFolder"] = "Open folder",
            ["Config.Reload"] = "Reload",
            ["Config.SaveFile"] = "Save file",
            ["Config.TableMode"] = "Table",
            ["Config.RawMode"] = "Raw text",
            ["Config.SearchTip"] = "Filter by key or value",
            ["Config.ColKey"] = "Key",
            ["Config.ColValue"] = "Value",
            ["Config.ColKind"] = "Type",
            ["Config.ColComment"] = "Comment",
            ["Config.NoPath"] = "No file path entered.",
            ["Config.ReadFailed"] = "Cannot read the file: {0}",
            ["Config.NotLoaded"] = "The file is not loaded yet — click Reload.",
            ["Config.NoChanges"] = "Nothing changed, nothing to save.",
            ["Config.WriteFailed"] = "Cannot write the file: {0}",
            ["Config.SavedAt"] = "Saved at {0}",
            ["Config.ChangedOnDisk"] = "Another tool changed this file after Cowork opened it. Press Reload to take the new contents (losing what you typed), or Overwrite anyway.",
            ["Config.ChangedOnDiskBanner"] = "The file changed on disk.",
            ["Config.Overwrite"] = "Overwrite anyway",
            ["Config.OverwroteSuffix"] = " (overwrote the external change)",
            ["Config.ShowChanges"] = "Show changes",
            ["Config.ShowChangesTip"] = "Compare what is about to be written with what is on disk",
            ["Config.ShowBackup"] = "Backup",
            ["Config.ShowBackupTip"] = "Compare the .cowork.bak file with the current contents, and restore it if needed",
            ["Config.NoBackup"] = "There is no .cowork.bak backup for this file yet.",
            ["Config.Restored"] = "Restored from the backup.",
            ["Msg.ConfigRestored"] = "Restored “{0}” from its backup.",
            ["Diff.PendingTitle"] = "Pending changes — {0}",
            ["Diff.BackupTitle"] = "Backup — {0}",
            ["Diff.LabelOnDisk"] = "what is on disk",
            ["Diff.LabelPending"] = "what will be written",
            ["Diff.LabelBackup"] = "the backup (.cowork.bak)",
            ["Diff.LabelCurrent"] = "the current contents",
            ["Diff.Summary"] = "{0} lines added, {1} removed.",
            ["Diff.Identical"] = "The two sides are identical.",
            ["Diff.TruncatedSuffix"] = " The changed block was too large to match line by line, so it is shown as a full removal followed by a full addition.",
            ["Diff.OnlyChanges"] = "Only show what changed",
            ["Diff.Restore"] = "Restore the backup",
            ["Diff.Close"] = "Close",
            ["Config.BackupSuffix"] = " (a .cowork.bak copy was created)",

            // ---------- Config value kinds ----------
            ["Kind.Number"] = "number",
            ["Kind.Boolean"] = "bool",
            ["Kind.Null"] = "null",
            ["Kind.String"] = "string",
            ["Kind.WarnNumber"] = "The value must be a number.",
            ["Kind.WarnBoolean"] = "The value must be true or false.",

            // ---------- Schedule (UI) ----------
            ["Schedule.Card"] = "Daily schedule",
            ["Schedule.EnableCheck"] = "Enable automatic scheduling for this app",
            ["Schedule.KindLabel"] = "Schedule type",
            ["Schedule.KindDaily"] = "Run at fixed times of day",
            ["Schedule.KindInterval"] = "Repeat at a fixed interval",
            ["Schedule.KindStartup"] = "Run once when Cowork opens",
            ["Schedule.KindManual"] = "Manual only",
            ["Schedule.TimesCard"] = "Times of day",
            ["Schedule.TimesHint"] = "Enter several times separated by commas. For example: 07:30, 12:00, 18:15",
            ["Schedule.IntervalCard"] = "Repeat interval",
            ["Schedule.EveryMinutes"] = "Every (minutes)",
            ["Schedule.WindowFrom"] = "Only between",
            ["Schedule.WindowFromTip"] = "Leave empty for no limit. For example 08:00",
            ["Schedule.WindowTo"] = "and",
            ["Schedule.WindowToTip"] = "Leave empty for no limit. For example 18:00",
            ["Schedule.DaysCard"] = "Days of the week",
            ["Schedule.DaysHint"] = "No day selected = run every day of the week.",
            ["Schedule.CatchUp"] = "Catch up if the machine was off or Cowork was closed at the due time",
            ["Schedule.SummaryLabel"] = "Summary:",
            ["Schedule.NextRunLabel"] = "Next run:",

            // ---------- Output ----------
            ["Output.Title"] = "Output of the current run",
            ["Output.LinesSuffix"] = "lines",
            ["Output.Hint"] = "Output is captured only when “Capture output” is on and the app does not run as administrator. Full logs live in the logs folder.",

            // ---------- History ----------
            ["History.Title"] = "Run history",
            ["History.OpenLogFolder"] = "Open log folder",
            ["History.Clear"] = "Clear history",
            ["History.ColStarted"] = "Started",
            ["History.ColApp"] = "App",
            ["History.ColTrigger"] = "Trigger",
            ["History.ColOutcome"] = "Outcome",
            ["History.ColExitCode"] = "Exit code",
            ["History.ColDuration"] = "Duration",
            ["History.ColNote"] = "Note",
            ["History.RunOutputTitle"] = "Output of the selected run:",
            ["History.OpenRunLog"] = "Open the log file",
            ["History.NoOutputFile"] = "this run captured no output (“Capture output” off, ran as administrator, or the log file has been pruned)",
            ["History.OutputEmpty"] = "the app printed nothing",
            ["History.OutputLines"] = "{0} lines",
            ["History.OutputTruncated"] = "showing the last {0} lines only — open the log file for everything",

            // ---------- Settings ----------
            ["Settings.AppearanceCard"] = "Appearance",
            ["Settings.ThemeLabel"] = "Colour theme",
            ["Settings.ThemeHint"] = "Theme changes apply immediately — no restart needed.",
            ["Settings.LanguageLabel"] = "Language",
            ["Settings.LanguageHint"] = "Language changes apply immediately across the whole interface.",
            ["Settings.BackgroundCard"] = "Background",
            ["Settings.SchedulerCheck"] = "Enable the scheduler (launch apps at the configured times)",
            ["Settings.MinimizeCheck"] = "Closing with X minimises to the system tray instead of quitting",
            ["Settings.StartupCheck"] = "Start with Windows (opens minimised)",
            ["Settings.BackgroundHint"] = "The scheduler only works while Cowork is running — including when it sits in the tray.",
            ["Settings.HistoryCard"] = "History & logs",
            ["Settings.RetentionLabel"] = "Days of run history to keep",
            ["Settings.OpenDataFolder"] = "Open data folder",
            ["Settings.OpenLogFolder"] = "Open log folder",
            ["Settings.DataHint"] = "Cowork data lives in %APPDATA%\\Cowork — backing up workspace.json backs up every app definition.",

            // ---------- Themes ----------
            ["Theme.Dark"] = "Dark",
            ["Theme.Light"] = "Light",
            ["Theme.Midnight"] = "Midnight",
            ["Theme.HighContrast"] = "High contrast",

            // ---------- Status bar & tray ----------
            ["Status.Ready"] = "Ready.",
            ["Status.Unsaved"] = "● Unsaved changes",
            ["Tray.Tooltip"] = "Cowork — daily app launcher",
            ["Tray.Open"] = "Open Cowork",
            ["Tray.Exit"] = "Quit Cowork",

            // ---------- Messages & dialogs ----------
            ["App.NewNamePrefix"] = "New app",
            ["App.NewNameFormat"] = "New app {0}",
            ["App.CopySuffix"] = " (copy)",
            ["App.Untitled"] = "(unnamed)",
            ["App.Ungrouped"] = "Ungrouped",
            ["Msg.AppAdded"] = "New app added. Pick the program it should run.",
            ["Msg.Duplicated"] = "Duplicated “{0}”.",
            ["Msg.DeleteConfirm"] = "Remove the app “{0}” from Cowork?\n\nConfig files and the program on disk are NOT deleted.",
            ["Msg.DeleteConfirmTitle"] = "Confirm deletion",
            ["Msg.Deleted"] = "Deleted “{0}”.",
            ["Msg.StopRequested"] = "Requested a stop for “{0}”.",
            ["Msg.NotRunning"] = "The app is not running.",
            ["Msg.StartedCount"] = "Launched {0} app(s).",
            ["Msg.StopAllRequested"] = "Requested a stop for every running app.",
            ["Msg.CannotRun"] = "“{0}” cannot run yet: its configuration is incomplete.",
            ["Msg.RunFailed"] = "“{0}”: {1}",
            ["Msg.ExitedWithError"] = "“{0}” finished with an error (code {1}).",
            ["Msg.ExitedWithCode"] = "Finished with exit code {0}.",
            ["Msg.SchedulerOn"] = "Scheduled runs are on.",
            ["Msg.SchedulerOff"] = "Scheduled runs are off.",
            ["Msg.Saved"] = "Saved at {0}.",
            ["Msg.SaveFailed"] = "Could not save: {0}",
            ["Msg.SaveFailedDialog"] = "Could not save the configuration:\n{0}",
            ["Msg.ScheduleChecked"] = "Ran one schedule check.",
            ["Msg.HistoryCleared"] = "Run history cleared.",
            ["Msg.FolderMissing"] = "Folder does not exist: {0}",
            ["Msg.FileMissing"] = "File does not exist: {0}",
            ["Msg.ProgramChosen"] = "“{0}” is now the command to run.",
            ["Msg.ConfigAdded"] = "Added {0} config file(s) to “{1}”.",
            ["Msg.ConfigAllExisting"] = "Every selected file is already in the list.",
            ["Msg.ExitWhileRunning"] = "Apps are still running under Cowork. Quitting now stops them.\n\nQuit anyway?",
            ["Msg.UnhandledError"] = "Cowork hit an unexpected error:\n\n{0}\n\nDetails went to the log. The app keeps running.",
            ["Dialog.PickProgram"] = "Pick the program to run",
            ["Dialog.ProgramFilter"] = "Programs (*.exe;*.bat;*.cmd;*.ps1)|*.exe;*.bat;*.cmd;*.ps1|All files (*.*)|*.*",
            ["Dialog.PickWorkingDir"] = "Pick the working directory",
            ["Dialog.PickScanFolder"] = "Pick the folder to scan",
            ["Dialog.PickConfigFile"] = "Pick a config file",
            ["Dialog.ConfigFilter"] = "Config (*.json;*.ini;*.xml;*.config;*.env;*.conf)|*.json;*.ini;*.xml;*.config;*.env;*.conf|All files (*.*)|*.*",

            // ---------- App state ----------
            ["State.Disabled"] = "Disabled",
            ["State.Starting"] = "Starting…",
            ["State.Running"] = "Running (PID {0})",
            ["State.Stopping"] = "Stopping…",
            ["State.Failed"] = "Failed",
            ["State.LastRunAt"] = "Last run {0}",
            ["State.NeverRun"] = "Never run",
            ["State.NeverRunShort"] = "Never run",
            ["State.ExitCodeSuffix"] = " · code {0}",
            ["State.Today"] = "today",

            // ---------- Enum labels ----------
            ["Outcome.Running"] = "Running",
            ["Outcome.Succeeded"] = "Succeeded",
            ["Outcome.Failed"] = "Failed",
            ["Outcome.Cancelled"] = "Stopped",
            ["Outcome.TimedOut"] = "Timed out",
            ["Outcome.NotStarted"] = "Did not start",
            ["Trigger.Manual"] = "Manual",
            ["Trigger.Schedule"] = "Schedule",
            ["Trigger.Startup"] = "On startup",
            ["Trigger.RunAll"] = "Run all",
            ["WindowStyle.Normal"] = "Normal",
            ["WindowStyle.Minimized"] = "Minimised",
            ["WindowStyle.Hidden"] = "Hidden",
            ["Day.Monday"] = "Mon",
            ["Day.Tuesday"] = "Tue",
            ["Day.Wednesday"] = "Wed",
            ["Day.Thursday"] = "Thu",
            ["Day.Friday"] = "Fri",
            ["Day.Saturday"] = "Sat",
            ["Day.Sunday"] = "Sun",

            // ---------- Duration ----------
            ["Duration.Seconds"] = "{0}s",
            ["Duration.Minutes"] = "{0}m{1}",
            ["Duration.Hours"] = "{0}h{1}",

            // ---------- Schedule summary (Core) ----------
            ["Sched.Off"] = "Schedule off",
            ["Sched.EveryDay"] = "every day",
            ["Sched.Manual"] = "Manual",
            ["Sched.Daily"] = "{0} · {1}",
            ["Sched.NoTimes"] = "No times set",
            ["Sched.Interval"] = "Every {0} · {1}",
            ["Sched.OnStartup"] = "When Cowork opens",
            ["Sched.Unknown"] = "Unknown",
            ["Sched.IntervalMinutes"] = "{0} min",
            ["Sched.IntervalHours"] = "{0} h",
            ["Sched.IntervalHoursMinutes"] = "{0}h{1}",

            // ---------- Validation (Core) ----------
            ["Val.NameRequired"] = "The app name cannot be empty.",
            ["Val.ExecutableRequired"] = "No program selected to run.",
            ["Val.ExecutableNotFound"] = "No file found at this path.",
            ["Val.WorkingDirMissing"] = "The working directory does not exist.",
            ["Val.TimeoutNegative"] = "The time limit cannot be negative.",
            ["Val.AdminNoOutput"] = "Running as administrator cannot capture output; the Output tab will stay empty.",
            ["Val.TimesRequired"] = "A time-of-day schedule needs at least one time.",
            ["Val.IntervalTooShort"] = "The repeat interval must be at least 1 minute.",
            ["Val.WindowOrder"] = "The start time must be earlier than the end time.",
            ["Val.ConfigPathMissing"] = "One config file has no path.",
            ["Val.ConfigFileNotFound"] = "Config file not found: {0}",

            // ---------- Config formats (Core) ----------
            ["Format.Auto"] = "Auto-detect",
            ["Format.Json"] = "JSON",
            ["Format.Ini"] = "INI / .env",
            ["Format.Xml"] = "XML",
            ["Format.PlainText"] = "Plain text",

            // ---------- Process (Core) ----------
            ["Proc.Disabled"] = "The app is disabled.",
            ["Proc.NoExecutable"] = "No program path configured.",
            ["Proc.AlreadyRunning"] = "The app is already running; this launch was skipped.",
            ["Proc.FileNotFound"] = "File not found: {0}",
            ["Proc.AccessDenied"] = "Access denied. Try turning on “Run as administrator”.",
            ["Proc.UacCancelled"] = "The user dismissed the elevation prompt (UAC).",
            ["Proc.WindowsError"] = "Windows error {0}: {1}",

            // ---------- Reading config files (Core) ----------
            ["Cfg.FileNotFound"] = "File not found: {0}",
            ["Cfg.InvalidJson"] = "Invalid JSON (line {0}): {1}",
            ["Cfg.EmptyJson"] = "The JSON file is empty.",
            ["Cfg.InvalidXml"] = "Invalid XML (line {0}): {1}",
            ["Cfg.NoRootElement"] = "The XML file has no root element.",

            // ---------- Scan dialogs ----------
            ["Scan.ConfigTitle"] = "Scan a folder for config files",
            ["Scan.ProgramTitle"] = "Scan a folder for programs",
            ["Scan.FolderLabel"] = "Folder to scan",
            ["Scan.IncludeLow"] = "Show Low confidence results too",
            ["Scan.IncludeLowConfigTip"] = "Files that only match by extension, buried deep in the tree",
            ["Scan.IncludeLowProgramTip"] = "Programs buried deep in the tree, or installers",
            ["Scan.MaxDepth"] = "Max depth:",
            ["Scan.ColPath"] = "Path",
            ["Scan.ColConfidence"] = "Confidence",
            ["Scan.ColFormat"] = "Format",
            ["Scan.ColKind"] = "Kind",
            ["Scan.ColSize"] = "Size",
            ["Scan.ColReason"] = "Why",
            ["Scan.SelectHigh"] = "Select High",
            ["Scan.SelectAll"] = "Select all",
            ["Scan.ClearSelection"] = "Clear selection",
            ["Scan.AddPrefix"] = "Add",
            ["Scan.AddSuffix"] = "selected file(s)",
            ["Scan.UseProgram"] = "Use this program",
            ["Scan.DoubleClickHint"] = "Double-click a row to pick it quickly.",
            ["Scan.CommandPreview"] = "Command that will be filled in",
            ["Scan.PowerShellHint"] = "A .ps1 file cannot launch itself, so Cowork calls it through powershell.exe.",
            ["Scan.PressToStart"] = "Click “Scan” to start.",
            ["Scan.Scanning"] = "Scanning…",
            ["Scan.Failed"] = "The scan failed.",
            ["Scan.RootFolder"] = "(root folder)",
            ["Scan.NothingTicked"] = "No file ticked yet.",
            ["Scan.ConfigNone"] = "Inspected {0} file(s), found no config files.",
            ["Scan.ConfigFound"] = "Found {0} file(s) ({1} at High confidence) among {2} inspected.",
            ["Scan.ProgramNone"] = "Inspected {0} file(s), found nothing runnable (.exe / .bat / .cmd / .ps1).",
            ["Scan.ProgramFound"] = "Found {0} program(s) ({1} at High confidence) among {2} inspected.",
            ["Scan.Truncated"] = " The result cap was reached — narrow the folder for a closer scan.",
            ["Confidence.High"] = "High",
            ["Confidence.Medium"] = "Medium",
            ["Confidence.Low"] = "Low",
            ["ProgramKind.Batch"] = "Batch",
            ["ProgramKind.PowerShell"] = "PowerShell",
            ["ProgramKind.Executable"] = "Executable",

            // ---------- Program scan reasons (Core) ----------
            ["Reason.Installer"] = "Looks like an installer or uninstaller",
            ["Reason.MatchesFolderName"] = "Matches the folder name “{0}”",
            ["Reason.LauncherName"] = "Name suggests an entry point (“{0}”)",
            ["Reason.LauncherPrefix"] = "Name starts with a launcher keyword",
            ["Reason.AtRoot"] = "Sits directly in the root folder",
            ["Reason.BuildOutput"] = "Sits inside the build output folder “{0}”",
            ["Reason.DeepInTree"] = "Buried deep in the folder tree",

            // ---------- Config scan reasons (Core) ----------
            ["Reason.ProjectManifest"] = "Project manifest, usually not runtime configuration",
            ["Reason.DotEnvTemplate"] = "Sample .env file, not the one in use",
            ["Reason.DotEnv"] = "Environment variable file .env",
            ["Reason.Template"] = "Sample file, not the configuration in use",
            ["Reason.ExtensionlessNamed"] = "Extensionless config file named “{0}”",
            ["Reason.ExtensionlessContains"] = "Extensionless name contains “config”/“setting”",
            ["Reason.RcFile"] = "rc-style config file ({0})",
            ["Reason.DotNetConfig"] = "Standard .NET application configuration",
            ["Reason.AspNetCoreConfig"] = "Standard ASP.NET Core configuration",
            ["Reason.SpringConfig"] = "Standard Spring configuration",
            ["Reason.NameContainsConfig"] = "File name contains “config”/“setting”",
            ["Reason.ConfigExtension"] = "The .config extension",
            ["Reason.StrongExtension"] = "The {0} extension is nearly always configuration",
            ["Reason.InConfigDirectory"] = "Sits inside the “{0}” folder",
            ["Reason.AtAppRoot"] = "Sits directly in the app root folder",
            ["Reason.ExtensionOnly"] = "Only matches the {0} extension",
            ["Reason.SyntaxProblem"] = "Syntax error, needs a second look",
            ["Reason.Unreadable"] = "The file could not be read",
            // ---------- Keep-alive ----------
            ["Trigger.KeepAlive"] = "Auto-restart",
            ["Val.RestartDelayNegative"] = "The restart delay cannot be negative.",
            ["Val.RestartLimitNegative"] = "The restart limit cannot be negative.",
            ["Overview.KeepAlive"] = "Keep this app running (restart it whenever it exits on its own)",
            ["Overview.KeepAliveHint"] = "Pressing Stop never triggers a restart. Pair it with the “Run once when Cowork opens” schedule so the app comes up as soon as Cowork does.",
            ["Overview.RestartDelay"] = "Wait before restarting (seconds)",
            ["Overview.RestartLimit"] = "Limit (per hour, 0 = unlimited)",
            ["Overview.RestartLimitHint"] = "At the limit Cowork gives up and reports it, instead of restarting a broken app forever.",
            ["State.WaitingRestart"] = "Restarting in {0}s (attempt {1})",
            ["Main.Restart"] = "↻  Restart",
            ["Main.RestartTip"] = "Stop, then run the selected app again",
            ["Settings.NotifyCheck"] = "Show a tray notification when an app fails or cannot be kept running",
            ["Msg.RestartRequested"] = "Restarting “{0}”.",
            ["Msg.KeepAliveRestarting"] = "Auto-restarting “{0}” (attempt {1}).",
            ["Msg.KeepAliveGaveUp"] = "“{0}” was restarted {1} times within {2} minutes; keep-alive is paused.",
            ["Msg.RestartCancelled"] = "Cancelled the restart of “{0}”.",
            ["Notify.FailedTitle"] = "App failed",
            ["Notify.FailedBody"] = "“{0}” exited with code {1}.",
            ["Notify.NotStartedBody"] = "“{0}” could not start: {1}",
            ["Notify.TimedOutBody"] = "“{0}” was stopped for running too long.",
            ["Notify.GaveUpTitle"] = "Could not keep it running",

            // ---------- Retry, exit codes, graceful stop, log pruning ----------
            ["Trigger.Retry"] = "Retry",
            ["Overview.RetryTitle"] = "Retry on failure",
            ["Overview.RetryCount"] = "Retries (0 = none)",
            ["Overview.RetryDelay"] = "Wait before retrying (seconds)",
            ["Overview.RetryHint"] = "For jobs that run and exit: when a run fails or times out, Cowork runs it again after the delay, up to this many times, and only raises a tray notification once every retry has failed. Pressing Stop never retries. Apps with “Keep this app running” are restarted already, so this is ignored for them.",
            ["Overview.SuccessExitCodes"] = "Exit codes that count as success",
            ["Overview.SuccessExitCodesHint"] = "Comma-separated, default 0. robocopy, for instance, returns 1 after copying files.",
            ["Overview.StopGrace"] = "Graceful stop timeout (seconds)",
            ["Overview.StopGraceHint"] = "On Stop, Cowork closes the main window or sends Ctrl+C to console apps, waits this long, then force-kills.",
            ["State.WaitingRetry"] = "Retrying in {0}s (attempt {1} of {2})",
            ["Val.RetryCountNegative"] = "The retry count cannot be negative.",
            ["Val.RetryDelayNegative"] = "The retry delay cannot be negative.",
            ["Val.StopGraceNegative"] = "The graceful stop timeout cannot be negative.",
            ["Val.RetryWithKeepAlive"] = "“Keep this app running” already restarts this app; the retry count will not be used.",
            ["Msg.RetryScheduled"] = "“{0}” failed; retrying in {1}s (attempt {2} of {3}).",
            ["Msg.Retrying"] = "Retrying “{0}” (attempt {1} of {2}).",
            ["Msg.RetryGaveUp"] = "“{0}” still fails after {1} retries.",
            ["Msg.RetryCancelled"] = "Cancelled the retry of “{0}”.",
            ["Notify.RetryGaveUpTitle"] = "Still failing after retries",
            ["Notify.RetryGaveUpBody"] = "“{0}” still fails after {1} retries. {2}",
            ["Notify.ReasonExitCode"] = "Exit code {0}.",
            ["Notify.ReasonTimedOut"] = "Stopped for running too long.",
            ["Settings.LogRetentionLabel"] = "Days of log files to keep",
            ["Settings.LogRetentionHint"] = "Each app writes one log file per day into the logs folder. Files older than this are deleted when Cowork opens and at the start of each day.",

            // ---------- Remote management ----------
            ["Trigger.Remote"] = "Remote",
            ["Settings.RemoteCard"] = "Remote management",
            ["Settings.HubUrl"] = "Hub address",
            ["Settings.HubToken"] = "Agent token",
            ["Settings.HubHint"] = "Cowork connects out to the hub at startup and stays connected. This machine's apps show up on the web, where they can be run, stopped and restarted. Leave the address empty to turn this off.",
            ["Settings.HubReconnect"] = "Reconnect",
            ["Settings.HubStatus"] = "Status:",
            ["HubLink.Disabled"] = "Off",
            ["HubLink.Connecting"] = "Connecting…",
            ["HubLink.Connected"] = "Connected",
            ["HubLink.Reconnecting"] = "Connection lost, retrying…",
            ["HubLink.Failed"] = "Cannot connect: {0}",
            ["Msg.RemoteRun"] = "Web command: run “{0}”.",
            ["Msg.RemoteStop"] = "Web command: stop “{0}”.",
            ["Msg.RemoteRestart"] = "Web command: restart “{0}”.",
            ["Msg.RemoteUnknownApp"] = "No app on this machine has that id.",
            ["Msg.RemoteDone"] = "Done.",
            ["Web.Appearance"] = "Appearance",
            ["Web.SwitchLanguage"] = "Tiếng Việt",
            ["Web.Login"] = "Sign in",
            ["Web.Password"] = "Password",
            ["Web.LoginFailed"] = "Wrong password.",
            ["Web.Logout"] = "Sign out",
            ["Web.Machines"] = "Machines",
            ["Web.Online"] = "Online",
            ["Web.NeverConnected"] = "Never connected",
            ["Web.LastSeen"] = "Offline · last seen {0}",
            ["Web.NoApps"] = "This machine has no apps yet.",
            ["Web.ColApp"] = "App",
            ["Web.ColState"] = "State",
            ["Web.ColLastRun"] = "Last run",
            ["Web.ColNextRun"] = "Next",
            ["Web.Run"] = "Run",
            ["Web.Stop"] = "Stop",
            ["Web.Restart"] = "Restart",
            ["Web.KeepAliveBadge"] = "keep-alive",
            ["Web.DisabledBadge"] = "disabled",
            ["Web.Sent"] = "“{0}”: {1}",
            ["Web.AgentRefused"] = "“{0}” could not do that: {1}",
            ["Web.MachineOffline"] = "The machine is offline.",
            ["Web.MachineUnknown"] = "Unknown machine.",
            ["Web.Timeout"] = "The machine did not respond.",
            ["Web.CommandFailed"] = "Could not send the command: {0}",

            // ---------- Machine admin page ----------
            ["Web.NavMachines"] = "Machines",
            ["Web.NavAgents"] = "Tokens",
            ["Web.AgentsTitle"] = "Machines and tokens",
            ["Web.AgentsIntro"] = "Each machine needs its own token. Paste it into the “Agent token” box in Cowork's Settings on that machine, then hit Reconnect.",
            ["Web.ColMachine"] = "Machine",
            ["Web.ColToken"] = "Token",
            ["Web.ColLink"] = "Link",
            ["Web.AddMachine"] = "Add machine",
            ["Web.NewMachineName"] = "New machine name",
            ["Web.GenerateToken"] = "Generate token",
            ["Web.Remove"] = "Revoke",
            ["Web.ConfirmRemove"] = "Revoke the token for “{0}”? That machine will not be able to reconnect.",
            ["Web.Cancel"] = "Cancel",
            ["Web.ShowToken"] = "Show",
            ["Web.HideToken"] = "Hide",
            ["Web.TokenHidden"] = "••••••••",
            ["Web.AgentAdded"] = "Added “{0}”. Copy the token below over to that machine.",
            ["Web.AgentRemoved"] = "Revoked the token for “{0}”.",
            ["Web.NameEmpty"] = "The machine needs a name.",
            ["Web.NameDuplicate"] = "A machine by that name already exists.",
            ["Web.TokenTooShort"] = "A token must be at least {0} characters long.",
            ["Web.TokenDuplicate"] = "That token already belongs to another machine.",
            ["Web.AgentNotFound"] = "No such machine.",
            ["Web.SaveFailed"] = "Could not write the machine list to disk, so the change was rolled back: {0}",
            ["Web.NoAgents"] = "No machine has a token yet.",

            ["Web.ViewScreen"] = "View screen",
            ["Web.ScreenTitle"] = "{0} · {1}",
            ["Web.ScreenTakenAt"] = "Taken at {0}",
            ["Web.ScreenRefresh"] = "Take again",
            ["Web.ScreenClose"] = "Close",
            ["Web.ScreenCapturing"] = "Taking a shot…",
            ["Web.ScreenMachineOffline"] = "The machine is offline, so nothing can be captured.",
            ["Web.ScreenUnknownApp"] = "That machine no longer has this app.",
            ["Web.ScreenNotRunning"] = "The app is not running, so there is nothing to capture.",
            ["Web.ScreenNoWindow"] = "The app is running but has no window — a background service or a hidden console cannot be captured.",
            ["Web.ScreenCaptureFailed"] = "Could not capture this app's window.",

            ["WebState.Idle"] = "Idle",
            ["WebState.Starting"] = "Starting",
            ["WebState.Running"] = "Running",
            ["WebState.Stopping"] = "Stopping",
            ["WebState.Failed"] = "Failed",
            ["WebState.WaitingRestart"] = "Waiting to restart",

            // ---------- Health check ----------
            ["Outcome.Unhealthy"] = "Hung",
            ["HealthProbe.None"] = "No probe",
            ["HealthProbe.TcpPort"] = "TCP port",
            ["HealthProbe.HttpGet"] = "HTTP URL",
            ["Overview.HealthCard"] = "Health check",
            ["Overview.HealthHint"] = "Catch an app that is still alive but hung: probe a port/URL periodically, or watch its output. When it is hung, Cowork stops it and records the run as “Hung”; apps with “Keep this app running” are restarted, apps with retries are run again.",
            ["Overview.HealthProbe"] = "Probe",
            ["Overview.HealthTarget"] = "Target",
            ["Overview.HealthTargetHint"] = "TCP port: 8080 or host:8080. HTTP: http://localhost:8080/health — a 2xx status means alive.",
            ["Overview.HealthInterval"] = "Check every (seconds)",
            ["Overview.HealthTimeout"] = "Response timeout (seconds)",
            ["Overview.HealthThreshold"] = "Consecutive failures before it counts as hung",
            ["Overview.HealthStartupGrace"] = "Skip checks for the first (seconds) after start",
            ["Overview.HealthOutputTitle"] = "Output watchdog",
            ["Overview.HealthSilence"] = "Hung when there is no output for (minutes, 0 = off)",
            ["Overview.HealthPatterns"] = "Failure patterns in output (one per line, regex, case-insensitive)",
            ["Overview.HealthOutputHint"] = "Only works when “Capture output” is on and the app does not run as administrator. Example patterns: FATAL, OutOfMemory, connection lost.",
            ["Health.ReasonSilence"] = "No output for {0} minutes.",
            ["Health.ReasonProbe"] = "Failed {0} checks in a row ({1}: {2}).",
            ["Health.ReasonPattern"] = "Output contained “{0}”.",
            ["Health.BadTarget"] = "invalid target “{0}”",
            ["Health.HttpStatus"] = "HTTP {0}",
            ["Health.ProbeTimeout"] = "no response within {0} seconds",
            ["Msg.Unhealthy"] = "“{0}” is hung: {1} Stopping it.",
            ["Notify.UnhealthyBody"] = "“{0}” was stopped because it hung. {1}",
            ["Notify.ReasonUnhealthy"] = "Hung: {0}",
            ["Val.HealthTargetRequired"] = "A probe is selected but the target is empty.",
            ["Val.HealthTcpTarget"] = "The TCP target must be a port (8080) or host:port.",
            ["Val.HealthHttpTarget"] = "The HTTP target must be an http:// or https:// address.",
            ["Val.HealthIntervalTooShort"] = "The health check interval must be at least 1 second.",
            ["Val.HealthTimeoutTooShort"] = "The response timeout must be at least 1 second.",
            ["Val.HealthThresholdTooLow"] = "The failure threshold must be at least 1.",
            ["Val.HealthGraceNegative"] = "The startup grace period cannot be negative.",
            ["Val.HealthSilenceNegative"] = "The silence limit cannot be negative.",
            ["Val.HealthOutputNotCaptured"] = "The output watchdog needs “Capture output” on and no administrator elevation; it will be ignored as configured.",
            ["Val.HealthPatternInvalid"] = "“{0}” is not a valid regex and will be matched as plain text.",

            // ---------- Dependencies between apps ----------
            ["DependencyWait.Completed"] = "Finished successfully",
            ["DependencyWait.Running"] = "Up and running",
            ["Overview.DependsOnCard"] = "Dependencies",
            ["Overview.DependsOnHint"] = "During “Run all”, this app starts only once every ticked app is ready. If a dependency fails or is skipped, this app is skipped too. Pressing ▶ Run on a single app ignores dependencies — that is the app you asked for.",
            ["Overview.DependsOnEmpty"] = "There is no other app to depend on yet.",
            ["Overview.DependsOnColApp"] = "Wait for",
            ["Overview.DependsOnColWait"] = "Wait until",
            ["Overview.DependsOnWaitHint"] = "“Finished successfully” suits jobs (back up, then compress). “Up and running” suits services — an app that is kept running never finishes.",
            ["Queue.SkipCycle"] = "“{0}” sits in a dependency cycle.",
            ["Queue.SkipMissing"] = "“{0}” waits for an app that is neither in this run nor already running.",
            ["Queue.SkipNeverCompletes"] = "“{0}” waits for “{1}” to finish, but that app is kept running and never finishes.",
            ["Queue.SkipDependencyFailed"] = "“{0}” was skipped because “{1}” did not succeed.",
            ["Queue.SkipCannotStart"] = "“{0}” could not be started.",
            ["Msg.RunAllQueued"] = "Running {0} apps in dependency order.",
            ["Msg.RunAllFinished"] = "Run finished: {0} succeeded, {1} failed, {2} skipped.",
            ["Notify.RunAllSkippedTitle"] = "Some apps were skipped",
            ["Val.DependencyUnknown"] = "“{0}” depends on an app that no longer exists.",
            ["Val.DependencyDisabled"] = "“{0}” depends on “{1}”, which is disabled, so it will be skipped during Run all.",
            ["Val.DependencyKeepAliveCompleted"] = "“{0}” waits for “{1}” to finish, but that app is kept running and never finishes. Switch it to “Up and running”.",
            ["Val.DependencyCycle"] = "Dependency cycle: {0}",

            // ---------- System event triggers ----------
            ["Trigger.SystemEvent"] = "System event",
            ["SystemEvent.Resume"] = "the machine waking up",
            ["SystemEvent.SessionUnlock"] = "the screen being unlocked",
            ["SystemEvent.NetworkAvailable"] = "the network coming back",
            ["Schedule.SystemCard"] = "Run on system events",
            ["Schedule.SystemHint"] = "Independent of the schedule kind above — an app can run both on a clock and on events. This covers what a clock misses: the machine waking up, the network dropping and returning.",
            ["Schedule.OnResume"] = "When the machine wakes from sleep",
            ["Schedule.OnUnlock"] = "When the screen is unlocked",
            ["Schedule.OnNetwork"] = "When the network comes back",
            ["Schedule.SystemDelay"] = "Wait after the event (seconds)",
            ["Schedule.SystemDelayHint"] = "Right after a wake-up the network and system services are not ready yet, so a few seconds of slack helps. Cowork ignores repeats of the same event within a minute, because Windows often fires several for a single wake-up.",
            ["Msg.SystemTriggerRun"] = "Running “{0}” because of {1}.",
            ["Val.SystemTriggerDelayNegative"] = "The delay after a system event cannot be negative.",

            // ---------- Alerts that leave the machine ----------
            ["Settings.AlertCard"] = "Outbound alerts",
            ["Settings.AlertHint"] = "A tray balloon only helps while you are sitting here. Fill in one of the three channels below and a failure at 2am reaches you anyway. Every configured channel is sent at once; one failing does not stop the others.",
            ["Settings.AlertEnable"] = "Send alerts outside the machine when an app fails",
            ["Settings.AlertWebhook"] = "Webhook URL",
            ["Settings.AlertWebhookHint"] = "Cowork POSTs a small JSON body with a “text” field — Slack, Discord, Teams and most webhook services read it as-is.",
            ["Settings.AlertTelegramToken"] = "Telegram bot token",
            ["Settings.AlertTelegramChat"] = "Chat id",
            ["Settings.AlertTelegramHint"] = "Create a bot with @BotFather for the token, then message the bot once to find the chat id. The token is stored in plain text in workspace.json.",
            ["Settings.AlertEmailTitle"] = "Email (SMTP)",
            ["Settings.AlertSmtpHost"] = "SMTP server",
            ["Settings.AlertSmtpPort"] = "Port",
            ["Settings.AlertSmtpSsl"] = "Use SSL/TLS",
            ["Settings.AlertSmtpUser"] = "Username",
            ["Settings.AlertSmtpPassword"] = "Password",
            ["Settings.AlertEmailFrom"] = "From",
            ["Settings.AlertEmailTo"] = "To",
            ["Settings.AlertEmailHint"] = "Separate several recipients with commas. The password is stored in plain text in workspace.json — with Gmail, use an app password rather than your account password.",
            ["Settings.AlertDedupe"] = "Quiet period for repeat alerts (minutes)",
            ["Settings.AlertTest"] = "Send a test",
            ["Alert.Channel.webhook"] = "webhook",
            ["Alert.Channel.telegram"] = "Telegram",
            ["Alert.Channel.email"] = "email",
            ["Alert.NoChannel"] = "No channel configured yet.",
            ["Alert.Channels"] = "Sending through: {0}.",
            ["Alert.ChannelsOff"] = "{0} configured, but the switch is off.",
            ["Alert.TestTitle"] = "Cowork test alert",
            ["Alert.TestBody"] = "If you can read this, the alert channel works.",
            ["Alert.TestSending"] = "Sending…",
            ["Alert.TestOk"] = "Sent through {0}.",
            ["Alert.TestFailed"] = "Could not send through {0} — see the log for details.",
            ["Alert.TestPartial"] = "Sent through {0}, failed on {1}.",
        };
}
