namespace Cowork.Core.Localization;

/// <summary>Bảng chuỗi tiếng Việt — cũng là bảng gốc dùng để lùi về khi thiếu khoá.</summary>
internal static class StringsVi
{
    internal static readonly IReadOnlyDictionary<string, string> Table =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            // ---------- Chung ----------
            ["Common.Cancel"] = "Huỷ",
            ["Common.Browse"] = "Chọn…",
            ["Common.BrowseFolder"] = "Đổi thư mục…",
            ["Common.Scan"] = "Quét",
            ["Common.Dash"] = "—",
            ["Common.AppName"] = "Cowork",

            // ---------- Cửa sổ chính ----------
            ["Main.Title"] = "Cowork — Quản lý app chạy hằng ngày",
            ["Main.Brand"] = "Cowork",
            ["Main.SchedulerToggle"] = "Chạy theo lịch",
            ["Main.SchedulerToggleTip"] = "Bật/tắt bộ đếm nền tự động chạy app theo lịch đã đặt",
            ["Main.Save"] = "Lưu",
            ["Main.SaveTip"] = "Lưu danh sách app và thiết lập (Ctrl+S)",
            ["Main.Run"] = "▶  Chạy",
            ["Main.RunTip"] = "Chạy app đang chọn (F5)",
            ["Main.Stop"] = "■  Dừng",
            ["Main.StopTip"] = "Dừng app đang chọn",
            ["Main.RunAll"] = "Chạy tất cả",
            ["Main.RunAllTip"] = "Chạy lần lượt mọi app đang bật",
            ["Main.StopAll"] = "Dừng tất cả",
            ["Main.CheckSchedule"] = "Kiểm tra lịch",
            ["Main.CheckScheduleTip"] = "Chạy ngay một vòng kiểm tra lịch thay vì chờ tới tick sau",

            // ---------- Danh sách app ----------
            ["AppList.Title"] = "Danh sách app",
            ["AppList.SearchTip"] = "Lọc theo tên, nhóm hoặc đường dẫn",
            ["AppList.Add"] = "+ Thêm",
            ["AppList.Duplicate"] = "Nhân bản",
            ["AppList.Delete"] = "Xoá",
            ["AppList.MoveUpTip"] = "Đưa lên trên (ảnh hưởng thứ tự Chạy tất cả)",
            ["AppList.MoveDownTip"] = "Đưa xuống dưới",
            ["AppList.NextRunPrefix"] = "Kế tiếp:",
            ["AppList.DisabledTip"] = "App đang tắt, sẽ không chạy",

            // ---------- Thẻ tab ----------
            ["Tab.Overview"] = "Tổng quan",
            ["Tab.Environment"] = "Biến môi trường",
            ["Tab.ConfigFiles"] = "File cấu hình",
            ["Tab.Schedule"] = "Lịch chạy",
            ["Tab.Output"] = "Nhật ký",
            ["Tab.History"] = "Lịch sử chạy",
            ["Tab.Settings"] = "Thiết lập",

            // ---------- Tổng quan ----------
            ["Overview.Empty"] = "Chưa chọn app nào. Bấm “+ Thêm” để tạo app đầu tiên.",
            ["Overview.InfoCard"] = "Thông tin app",
            ["Overview.Name"] = "Tên app",
            ["Overview.Group"] = "Nhóm",
            ["Overview.GroupTip"] = "Ví dụ: Backup, Báo cáo sáng, Dịch vụ nền",
            ["Overview.Description"] = "Mô tả",
            ["Overview.EnabledCheck"] = "Bật app này (bỏ chọn thì không chạy tay lẫn theo lịch)",
            ["Overview.CommandCard"] = "Lệnh chạy",
            ["Overview.Executable"] = "Chương trình (.exe / .bat / .cmd / .ps1)",
            ["Overview.PickFileTip"] = "Chỉ đích danh một file",
            ["Overview.ScanFolder"] = "Quét thư mục…",
            ["Overview.ScanProgramTip"] = "Dò tìm .exe/.bat/.cmd/.ps1 trong một thư mục",
            ["Overview.Arguments"] = "Tham số dòng lệnh",
            ["Overview.ArgumentsHint"] = "Hỗ trợ biến môi trường dạng %USERPROFILE%. Đường dẫn có dấu cách nhớ bọc trong nháy kép.",
            ["Overview.WorkingDir"] = "Thư mục làm việc",
            ["Overview.WorkingDirHint"] = "Để trống thì Cowork dùng thư mục chứa file chương trình.",
            ["Overview.RunOptionsCard"] = "Tuỳ chọn khi chạy",
            ["Overview.SingleInstance"] = "Không chạy chồng (chặn nếu instance cũ còn sống)",
            ["Overview.CaptureOutput"] = "Thu nhật ký output vào Cowork",
            ["Overview.RunAsAdmin"] = "Chạy với quyền quản trị (UAC)",
            ["Overview.RunAsAdminTip"] = "Bật cái này thì không thu được output",
            ["Overview.WindowStyle"] = "Kiểu cửa sổ",
            ["Overview.Timeout"] = "Tự dừng sau (phút, 0 = không giới hạn)",
            ["Overview.StatusCard"] = "Tình trạng",
            ["Overview.StatusLabel"] = "Trạng thái:",
            ["Overview.LastRunLabel"] = "Chạy lần cuối:",
            ["Overview.ScheduleLabel"] = "Lịch:",
            ["Overview.OpenAppFolder"] = "Mở thư mục chứa app",

            // ---------- Biến môi trường ----------
            ["Env.Title"] = "Biến môi trường riêng của app",
            ["Env.Hint"] = "Các biến này chỉ áp dụng cho tiến trình con do Cowork khởi chạy, không ảnh hưởng hệ thống. Giá trị hỗ trợ %BIEN_KHAC%.",
            ["Env.Add"] = "+ Thêm biến",
            ["Env.ColName"] = "Tên biến",
            ["Env.ColValue"] = "Giá trị",
            ["Env.DefaultName"] = "TEN_BIEN",
            ["Env.Remove"] = "Xoá",

            // ---------- File cấu hình ----------
            ["Config.ListTitle"] = "File cấu hình",
            ["Config.ScanTip"] = "Tự dò tìm file cấu hình trong thư mục làm việc của app",
            ["Config.AddManual"] = "+ Thêm file thủ công",
            ["Config.Remove"] = "Bỏ file khỏi danh sách",
            ["Config.PathLabel"] = "Đường dẫn file",
            ["Config.PickFile"] = "Chọn file…",
            ["Config.OpenFolder"] = "Mở thư mục",
            ["Config.Reload"] = "Tải lại",
            ["Config.SaveFile"] = "Lưu file",
            ["Config.TableMode"] = "Dạng bảng",
            ["Config.RawMode"] = "Sửa nguồn",
            ["Config.SearchTip"] = "Lọc theo tên khoá hoặc giá trị",
            ["Config.ColKey"] = "Khoá",
            ["Config.ColValue"] = "Giá trị",
            ["Config.ColKind"] = "Kiểu",
            ["Config.ColComment"] = "Ghi chú",
            ["Config.NoPath"] = "Chưa nhập đường dẫn file.",
            ["Config.ReadFailed"] = "Không đọc được file: {0}",
            ["Config.NotLoaded"] = "Chưa nạp được file, hãy bấm Tải lại.",
            ["Config.NoChanges"] = "Không có thay đổi nào để lưu.",
            ["Config.WriteFailed"] = "Không ghi được file: {0}",
            ["Config.SavedAt"] = "Đã lưu lúc {0}",
            ["Config.BackupSuffix"] = " (đã tạo bản sao .cowork.bak)",

            // ---------- Kiểu giá trị cấu hình ----------
            ["Kind.Number"] = "số",
            ["Kind.Boolean"] = "bool",
            ["Kind.Null"] = "null",
            ["Kind.String"] = "chuỗi",
            ["Kind.WarnNumber"] = "Giá trị phải là số.",
            ["Kind.WarnBoolean"] = "Giá trị phải là true hoặc false.",

            // ---------- Lịch chạy (giao diện) ----------
            ["Schedule.Card"] = "Lịch chạy hằng ngày",
            ["Schedule.EnableCheck"] = "Bật lịch tự động cho app này",
            ["Schedule.KindLabel"] = "Kiểu lịch",
            ["Schedule.KindDaily"] = "Chạy vào các mốc giờ cố định",
            ["Schedule.KindInterval"] = "Chạy lặp lại theo chu kỳ",
            ["Schedule.KindStartup"] = "Chạy một lần khi mở Cowork",
            ["Schedule.KindManual"] = "Chỉ chạy thủ công",
            ["Schedule.TimesCard"] = "Mốc giờ trong ngày",
            ["Schedule.TimesHint"] = "Nhập nhiều mốc, cách nhau bằng dấu phẩy. Ví dụ: 07:30, 12:00, 18:15",
            ["Schedule.IntervalCard"] = "Chu kỳ lặp",
            ["Schedule.EveryMinutes"] = "Mỗi (phút)",
            ["Schedule.WindowFrom"] = "Chỉ chạy từ",
            ["Schedule.WindowFromTip"] = "Bỏ trống nếu không giới hạn. Ví dụ 08:00",
            ["Schedule.WindowTo"] = "Đến",
            ["Schedule.WindowToTip"] = "Bỏ trống nếu không giới hạn. Ví dụ 18:00",
            ["Schedule.DaysCard"] = "Ngày trong tuần",
            ["Schedule.DaysHint"] = "Không chọn ngày nào = chạy mọi ngày trong tuần.",
            ["Schedule.CatchUp"] = "Chạy bù nếu lúc tới hạn máy đang tắt hoặc Cowork chưa mở",
            ["Schedule.SummaryLabel"] = "Tóm tắt:",
            ["Schedule.NextRunLabel"] = "Lần chạy kế tiếp:",

            // ---------- Nhật ký ----------
            ["Output.Title"] = "Output của lần chạy hiện tại",
            ["Output.LinesSuffix"] = "dòng",
            ["Output.Hint"] = "Output chỉ được thu khi bật “Thu nhật ký output” và không chạy quyền admin. Log đầy đủ nằm trong thư mục logs.",

            // ---------- Lịch sử ----------
            ["History.Title"] = "Lịch sử các lần chạy",
            ["History.OpenLogFolder"] = "Mở thư mục log",
            ["History.Clear"] = "Xoá lịch sử",
            ["History.ColStarted"] = "Bắt đầu",
            ["History.ColApp"] = "App",
            ["History.ColTrigger"] = "Nguồn",
            ["History.ColOutcome"] = "Kết quả",
            ["History.ColExitCode"] = "Mã thoát",
            ["History.ColDuration"] = "Thời lượng",
            ["History.ColNote"] = "Ghi chú",

            // ---------- Thiết lập ----------
            ["Settings.AppearanceCard"] = "Giao diện",
            ["Settings.ThemeLabel"] = "Chủ đề màu",
            ["Settings.ThemeHint"] = "Đổi chủ đề áp dụng ngay, không cần khởi động lại Cowork.",
            ["Settings.LanguageLabel"] = "Ngôn ngữ",
            ["Settings.LanguageHint"] = "Đổi ngôn ngữ áp dụng ngay cho toàn bộ giao diện.",
            ["Settings.BackgroundCard"] = "Chạy nền",
            ["Settings.SchedulerCheck"] = "Bật bộ lập lịch (tự chạy app theo giờ đã đặt)",
            ["Settings.MinimizeCheck"] = "Bấm X thì thu nhỏ xuống khay hệ thống thay vì thoát",
            ["Settings.StartupCheck"] = "Khởi động cùng Windows (mở ở chế độ thu nhỏ)",
            ["Settings.BackgroundHint"] = "Bộ lập lịch chỉ hoạt động khi Cowork còn đang chạy — kể cả khi đã thu nhỏ xuống khay.",
            ["Settings.HistoryCard"] = "Lịch sử & nhật ký",
            ["Settings.RetentionLabel"] = "Số ngày giữ lịch sử chạy",
            ["Settings.OpenDataFolder"] = "Mở thư mục dữ liệu",
            ["Settings.OpenLogFolder"] = "Mở thư mục log",
            ["Settings.DataHint"] = "Dữ liệu Cowork nằm trong %APPDATA%\\Cowork — sao lưu workspace.json là sao lưu được toàn bộ cấu hình app.",

            // ---------- Chủ đề ----------
            ["Theme.Dark"] = "Tối",
            ["Theme.Light"] = "Sáng",
            ["Theme.Midnight"] = "Nửa đêm",
            ["Theme.HighContrast"] = "Tương phản cao",

            // ---------- Thanh trạng thái & khay ----------
            ["Status.Ready"] = "Sẵn sàng.",
            ["Status.Unsaved"] = "● Có thay đổi chưa lưu",
            ["Tray.Tooltip"] = "Cowork — quản lý app chạy hằng ngày",
            ["Tray.Open"] = "Mở Cowork",
            ["Tray.Exit"] = "Thoát Cowork",

            // ---------- Thông báo & hộp thoại ----------
            ["App.NewNamePrefix"] = "App mới",
            ["App.NewNameFormat"] = "App mới {0}",
            ["App.CopySuffix"] = " (bản sao)",
            ["App.Untitled"] = "(chưa đặt tên)",
            ["App.Ungrouped"] = "Chưa phân nhóm",
            ["Msg.AppAdded"] = "Đã thêm app mới. Hãy chọn file chương trình cần chạy.",
            ["Msg.Duplicated"] = "Đã nhân bản “{0}”.",
            ["Msg.DeleteConfirm"] = "Xoá app “{0}” khỏi Cowork?\n\nFile cấu hình và chương trình trên đĩa KHÔNG bị xoá.",
            ["Msg.DeleteConfirmTitle"] = "Xác nhận xoá",
            ["Msg.Deleted"] = "Đã xoá “{0}”.",
            ["Msg.StopRequested"] = "Đã yêu cầu dừng “{0}”.",
            ["Msg.NotRunning"] = "App không chạy.",
            ["Msg.StartedCount"] = "Đã khởi chạy {0} app.",
            ["Msg.StopAllRequested"] = "Đã yêu cầu dừng tất cả app đang chạy.",
            ["Msg.CannotRun"] = "“{0}” chưa chạy được: cấu hình còn thiếu.",
            ["Msg.RunFailed"] = "“{0}”: {1}",
            ["Msg.ExitedWithError"] = "“{0}” kết thúc lỗi (mã {1}).",
            ["Msg.ExitedWithCode"] = "Kết thúc với mã thoát {0}.",
            ["Msg.SchedulerOn"] = "Đã bật chạy theo lịch.",
            ["Msg.SchedulerOff"] = "Đã tắt chạy theo lịch.",
            ["Msg.Saved"] = "Đã lưu lúc {0}.",
            ["Msg.SaveFailed"] = "Không lưu được: {0}",
            ["Msg.SaveFailedDialog"] = "Không lưu được cấu hình:\n{0}",
            ["Msg.ScheduleChecked"] = "Đã kiểm tra lịch một lượt.",
            ["Msg.HistoryCleared"] = "Đã xoá lịch sử chạy.",
            ["Msg.FolderMissing"] = "Thư mục không tồn tại: {0}",
            ["Msg.FileMissing"] = "File không tồn tại: {0}",
            ["Msg.ProgramChosen"] = "Đã chọn “{0}” làm lệnh chạy.",
            ["Msg.ConfigAdded"] = "Đã thêm {0} file cấu hình vào “{1}”.",
            ["Msg.ConfigAllExisting"] = "Các file đã chọn đều có sẵn trong danh sách.",
            ["Msg.ExitWhileRunning"] = "Đang có app chạy dưới quyền Cowork. Thoát bây giờ sẽ dừng chúng.\n\nVẫn thoát?",
            ["Msg.UnhandledError"] = "Cowork gặp lỗi ngoài dự kiến:\n\n{0}\n\nChi tiết đã được ghi vào log. Ứng dụng vẫn tiếp tục chạy.",
            ["Dialog.PickProgram"] = "Chọn chương trình cần chạy",
            ["Dialog.ProgramFilter"] = "Chương trình (*.exe;*.bat;*.cmd;*.ps1)|*.exe;*.bat;*.cmd;*.ps1|Tất cả (*.*)|*.*",
            ["Dialog.PickWorkingDir"] = "Chọn thư mục làm việc",
            ["Dialog.PickScanFolder"] = "Chọn thư mục cần quét",
            ["Dialog.PickConfigFile"] = "Chọn file cấu hình",
            ["Dialog.ConfigFilter"] = "Cấu hình (*.json;*.ini;*.xml;*.config;*.env;*.conf)|*.json;*.ini;*.xml;*.config;*.env;*.conf|Tất cả (*.*)|*.*",

            // ---------- Trạng thái app ----------
            ["State.Disabled"] = "Đã tắt",
            ["State.Starting"] = "Đang khởi động…",
            ["State.Running"] = "Đang chạy (PID {0})",
            ["State.Stopping"] = "Đang dừng…",
            ["State.Failed"] = "Lỗi",
            ["State.LastRunAt"] = "Chạy lần cuối {0}",
            ["State.NeverRun"] = "Chưa chạy lần nào",
            ["State.NeverRunShort"] = "Chưa chạy",
            ["State.ExitCodeSuffix"] = " · mã {0}",
            ["State.Today"] = "hôm nay",

            // ---------- Nhãn enum ----------
            ["Outcome.Running"] = "Đang chạy",
            ["Outcome.Succeeded"] = "Thành công",
            ["Outcome.Failed"] = "Lỗi",
            ["Outcome.Cancelled"] = "Đã dừng",
            ["Outcome.TimedOut"] = "Quá giờ",
            ["Outcome.NotStarted"] = "Không chạy được",
            ["Trigger.Manual"] = "Thủ công",
            ["Trigger.Schedule"] = "Theo lịch",
            ["Trigger.Startup"] = "Khi mở app",
            ["Trigger.RunAll"] = "Chạy tất cả",
            ["WindowStyle.Normal"] = "Bình thường",
            ["WindowStyle.Minimized"] = "Thu nhỏ",
            ["WindowStyle.Hidden"] = "Ẩn hoàn toàn",
            ["Day.Monday"] = "T2",
            ["Day.Tuesday"] = "T3",
            ["Day.Wednesday"] = "T4",
            ["Day.Thursday"] = "T5",
            ["Day.Friday"] = "T6",
            ["Day.Saturday"] = "T7",
            ["Day.Sunday"] = "CN",

            // ---------- Thời lượng ----------
            ["Duration.Seconds"] = "{0}s",
            ["Duration.Minutes"] = "{0}p{1}",
            ["Duration.Hours"] = "{0}g{1}",

            // ---------- Tóm tắt lịch (Core) ----------
            ["Sched.Off"] = "Tắt lịch",
            ["Sched.EveryDay"] = "mỗi ngày",
            ["Sched.Manual"] = "Thủ công",
            ["Sched.Daily"] = "{0} · {1}",
            ["Sched.NoTimes"] = "Chưa đặt mốc giờ",
            ["Sched.Interval"] = "Mỗi {0} · {1}",
            ["Sched.OnStartup"] = "Khi mở Cowork",
            ["Sched.Unknown"] = "Không xác định",
            ["Sched.IntervalMinutes"] = "{0} phút",
            ["Sched.IntervalHours"] = "{0} giờ",
            ["Sched.IntervalHoursMinutes"] = "{0}g{1}",

            // ---------- Kiểm tra cấu hình (Core) ----------
            ["Val.NameRequired"] = "Tên app không được để trống.",
            ["Val.ExecutableRequired"] = "Chưa chọn chương trình để chạy.",
            ["Val.ExecutableNotFound"] = "Không tìm thấy file tại đường dẫn này.",
            ["Val.WorkingDirMissing"] = "Thư mục làm việc không tồn tại.",
            ["Val.TimeoutNegative"] = "Thời gian tối đa không được âm.",
            ["Val.AdminNoOutput"] = "Chạy quyền admin thì không thu được output; mục Nhật ký sẽ trống.",
            ["Val.TimesRequired"] = "Lịch theo giờ cần ít nhất một mốc giờ.",
            ["Val.IntervalTooShort"] = "Chu kỳ lặp tối thiểu là 1 phút.",
            ["Val.WindowOrder"] = "Giờ bắt đầu phải sớm hơn giờ kết thúc.",
            ["Val.ConfigPathMissing"] = "Có file cấu hình chưa nhập đường dẫn.",
            ["Val.ConfigFileNotFound"] = "Không tìm thấy file cấu hình: {0}",

            // ---------- Định dạng cấu hình (Core) ----------
            ["Format.Auto"] = "Tự nhận",
            ["Format.Json"] = "JSON",
            ["Format.Ini"] = "INI / .env",
            ["Format.Xml"] = "XML",
            ["Format.PlainText"] = "Văn bản",

            // ---------- Tiến trình (Core) ----------
            ["Proc.Disabled"] = "App đang bị tắt.",
            ["Proc.NoExecutable"] = "Chưa khai báo đường dẫn chương trình.",
            ["Proc.AlreadyRunning"] = "App đang chạy, bỏ qua lần khởi chạy này.",
            ["Proc.FileNotFound"] = "Không tìm thấy file: {0}",
            ["Proc.AccessDenied"] = "Bị từ chối quyền truy cập. Thử bật “Chạy quyền admin”.",
            ["Proc.UacCancelled"] = "Người dùng đã huỷ hộp thoại nâng quyền (UAC).",
            ["Proc.WindowsError"] = "Lỗi Windows {0}: {1}",

            // ---------- Đọc file cấu hình (Core) ----------
            ["Cfg.FileNotFound"] = "Không tìm thấy file: {0}",
            ["Cfg.InvalidJson"] = "JSON không hợp lệ (dòng {0}): {1}",
            ["Cfg.EmptyJson"] = "File JSON rỗng.",
            ["Cfg.InvalidXml"] = "XML không hợp lệ (dòng {0}): {1}",
            ["Cfg.NoRootElement"] = "File XML không có phần tử gốc.",

            // ---------- Hộp thoại quét ----------
            ["Scan.ConfigTitle"] = "Quét thư mục tìm file cấu hình",
            ["Scan.ProgramTitle"] = "Quét thư mục tìm chương trình",
            ["Scan.FolderLabel"] = "Thư mục cần quét",
            ["Scan.IncludeLow"] = "Hiện cả kết quả tin cậy Thấp",
            ["Scan.IncludeLowConfigTip"] = "Các file chỉ khớp phần mở rộng, nằm sâu trong cây thư mục",
            ["Scan.IncludeLowProgramTip"] = "Chương trình nằm sâu trong cây thư mục, hoặc trình cài đặt",
            ["Scan.MaxDepth"] = "Độ sâu tối đa:",
            ["Scan.ColPath"] = "Đường dẫn",
            ["Scan.ColConfidence"] = "Tin cậy",
            ["Scan.ColFormat"] = "Định dạng",
            ["Scan.ColKind"] = "Loại",
            ["Scan.ColSize"] = "Cỡ",
            ["Scan.ColReason"] = "Vì sao",
            ["Scan.SelectHigh"] = "Chọn mức Cao",
            ["Scan.SelectAll"] = "Chọn tất cả",
            ["Scan.ClearSelection"] = "Bỏ chọn hết",
            ["Scan.AddPrefix"] = "Thêm",
            ["Scan.AddSuffix"] = "file đã chọn",
            ["Scan.UseProgram"] = "Dùng chương trình này",
            ["Scan.DoubleClickHint"] = "Nháy đúp vào một dòng để chọn nhanh.",
            ["Scan.CommandPreview"] = "Lệnh sẽ được điền vào app",
            ["Scan.PowerShellHint"] = "File .ps1 không tự chạy được nên Cowork gọi qua powershell.exe.",
            ["Scan.PressToStart"] = "Bấm “Quét” để bắt đầu.",
            ["Scan.Scanning"] = "Đang quét…",
            ["Scan.Failed"] = "Quét thất bại.",
            ["Scan.RootFolder"] = "(thư mục gốc)",
            ["Scan.NothingTicked"] = "Chưa tick file nào.",
            ["Scan.ConfigNone"] = "Đã xem {0} file, không thấy file cấu hình nào.",
            ["Scan.ConfigFound"] = "Tìm thấy {0} file ({1} ở mức tin cậy Cao) trong {2} file đã xem.",
            ["Scan.ProgramNone"] = "Đã xem {0} file, không thấy chương trình nào chạy được (.exe / .bat / .cmd / .ps1).",
            ["Scan.ProgramFound"] = "Tìm thấy {0} chương trình ({1} ở mức tin cậy Cao) trong {2} file đã xem.",
            ["Scan.Truncated"] = " Đã đạt trần kết quả — thu hẹp thư mục để quét kỹ hơn.",
            ["Confidence.High"] = "Cao",
            ["Confidence.Medium"] = "Vừa",
            ["Confidence.Low"] = "Thấp",
            ["ProgramKind.Batch"] = "Batch",
            ["ProgramKind.PowerShell"] = "PowerShell",
            ["ProgramKind.Executable"] = "Chương trình",

            // ---------- Lý do khi quét chương trình (Core) ----------
            ["Reason.Installer"] = "Có vẻ là trình cài đặt/gỡ cài đặt",
            ["Reason.MatchesFolderName"] = "Trùng tên thư mục “{0}”",
            ["Reason.LauncherName"] = "Tên gợi ý điểm khởi chạy (“{0}”)",
            ["Reason.LauncherPrefix"] = "Tên bắt đầu bằng từ khoá khởi chạy",
            ["Reason.AtRoot"] = "Nằm ngay thư mục gốc",
            ["Reason.BuildOutput"] = "Nằm trong thư mục kết quả build “{0}”",
            ["Reason.DeepInTree"] = "Nằm sâu trong cây thư mục",

            // ---------- Lý do khi quét cấu hình (Core) ----------
            ["Reason.ProjectManifest"] = "Manifest dự án, thường không phải cấu hình lúc chạy",
            ["Reason.DotEnvTemplate"] = "File .env mẫu, không phải cấu hình đang dùng",
            ["Reason.DotEnv"] = "File biến môi trường .env",
            ["Reason.Template"] = "File mẫu, không phải cấu hình đang dùng",
            ["Reason.ExtensionlessNamed"] = "File cấu hình không đuôi, tên “{0}”",
            ["Reason.ExtensionlessContains"] = "Tên file không đuôi chứa “config”/“setting”",
            ["Reason.RcFile"] = "File cấu hình kiểu rc ({0})",
            ["Reason.DotNetConfig"] = "Cấu hình chuẩn của ứng dụng .NET",
            ["Reason.AspNetCoreConfig"] = "Cấu hình chuẩn của ASP.NET Core",
            ["Reason.SpringConfig"] = "Cấu hình chuẩn của Spring",
            ["Reason.NameContainsConfig"] = "Tên file chứa “config”/“setting”",
            ["Reason.ConfigExtension"] = "Phần mở rộng .config",
            ["Reason.StrongExtension"] = "Phần mở rộng {0} hầu như luôn là cấu hình",
            ["Reason.InConfigDirectory"] = "Nằm trong thư mục “{0}”",
            ["Reason.AtAppRoot"] = "Nằm ngay thư mục gốc của app",
            ["Reason.ExtensionOnly"] = "Chỉ khớp phần mở rộng {0}",
            ["Reason.SyntaxProblem"] = "Sai cú pháp, cần kiểm tra lại",
            ["Reason.Unreadable"] = "Không đọc được file",
            // ---------- Giữ app luôn chạy ----------
            ["Trigger.KeepAlive"] = "Tự khởi động lại",
            ["Val.RestartDelayNegative"] = "Thời gian chờ khởi động lại không được âm.",
            ["Val.RestartLimitNegative"] = "Số lần khởi động lại tối đa không được âm.",
            ["Overview.KeepAlive"] = "Giữ app luôn chạy (tự khởi động lại khi app tự thoát)",
            ["Overview.KeepAliveHint"] = "Bấm Dừng thì không khởi động lại. Kết hợp với lịch “Chạy một lần khi mở Cowork” để app tự lên ngay khi mở Cowork.",
            ["Overview.RestartDelay"] = "Chờ trước khi chạy lại (giây)",
            ["Overview.RestartLimit"] = "Tối đa (lần / giờ, 0 = không giới hạn)",
            ["Overview.RestartLimitHint"] = "Chạm trần thì Cowork bỏ cuộc và báo lỗi, thay vì khởi động lại vô tận một app đã hỏng hẳn.",
            ["State.WaitingRestart"] = "Sẽ khởi động lại sau {0}s (lần {1})",
            ["Main.Restart"] = "↻  Khởi động lại",
            ["Main.RestartTip"] = "Dừng rồi chạy lại app đang chọn",
            ["Settings.NotifyCheck"] = "Thông báo ở khay hệ thống khi app chạy lỗi hoặc không giữ chạy được",
            ["Msg.RestartRequested"] = "Đang khởi động lại “{0}”.",
            ["Msg.KeepAliveRestarting"] = "Tự khởi động lại “{0}” (lần {1}).",
            ["Msg.KeepAliveGaveUp"] = "“{0}” đã tự khởi động lại {1} lần trong {2} phút, tạm dừng giữ chạy.",
            ["Msg.RestartCancelled"] = "Đã huỷ khởi động lại “{0}”.",
            ["Notify.FailedTitle"] = "App chạy lỗi",
            ["Notify.FailedBody"] = "“{0}” kết thúc với mã thoát {1}.",
            ["Notify.NotStartedBody"] = "“{0}” không chạy được: {1}",
            ["Notify.TimedOutBody"] = "“{0}” bị dừng vì quá thời gian cho phép.",
            ["Notify.GaveUpTitle"] = "Không giữ chạy được",

            // ---------- Thử lại khi lỗi, mã thoát, dừng lịch sự, dọn log ----------
            ["Trigger.Retry"] = "Thử lại",
            ["Overview.RetryTitle"] = "Thử lại khi lỗi",
            ["Overview.RetryCount"] = "Số lần thử lại (0 = không thử lại)",
            ["Overview.RetryDelay"] = "Chờ trước khi thử lại (giây)",
            ["Overview.RetryHint"] = "Dành cho job chạy xong là thoát: kết thúc lỗi hay quá giờ thì Cowork chạy lại sau khoảng chờ, tối đa số lần đã đặt, và chỉ báo ở khay khi hết lượt vẫn lỗi. Bấm Dừng thì không thử lại. App bật “Giữ app luôn chạy” đã được khởi động lại nên không dùng mục này.",
            ["Overview.SuccessExitCodes"] = "Mã thoát coi là thành công",
            ["Overview.SuccessExitCodesHint"] = "Cách nhau bằng dấu phẩy, mặc định 0. Ví dụ robocopy trả 1 khi đã sao chép xong.",
            ["Overview.StopGrace"] = "Chờ dừng lịch sự tối đa (giây)",
            ["Overview.StopGraceHint"] = "Khi bấm Dừng, Cowork đóng cửa sổ chính hoặc gửi Ctrl+C cho app console, chờ ngần này giây rồi mới buộc dừng.",
            ["State.WaitingRetry"] = "Sẽ thử lại sau {0}s (lần {1}/{2})",
            ["Val.RetryCountNegative"] = "Số lần thử lại không được âm.",
            ["Val.RetryDelayNegative"] = "Thời gian chờ thử lại không được âm.",
            ["Val.StopGraceNegative"] = "Thời gian chờ dừng lịch sự không được âm.",
            ["Val.RetryWithKeepAlive"] = "App bật “Giữ app luôn chạy” đã được tự khởi động lại; số lần thử lại sẽ không được dùng.",
            ["Msg.RetryScheduled"] = "“{0}” kết thúc lỗi, sẽ thử lại sau {1}s (lần {2}/{3}).",
            ["Msg.Retrying"] = "Thử lại “{0}” (lần {1}/{2}).",
            ["Msg.RetryGaveUp"] = "“{0}” vẫn lỗi sau {1} lần thử lại.",
            ["Msg.RetryCancelled"] = "Đã huỷ thử lại “{0}”.",
            ["Notify.RetryGaveUpTitle"] = "Thử lại vẫn lỗi",
            ["Notify.RetryGaveUpBody"] = "“{0}” vẫn lỗi sau {1} lần thử lại. {2}",
            ["Notify.ReasonExitCode"] = "Mã thoát {0}.",
            ["Notify.ReasonTimedOut"] = "Bị dừng vì quá thời gian cho phép.",
            ["Settings.LogRetentionLabel"] = "Số ngày giữ file log",
            ["Settings.LogRetentionHint"] = "Mỗi app mỗi ngày một file log trong thư mục logs. File cũ hơn số ngày này bị xoá lúc mở Cowork và vào đầu mỗi ngày.",

            // ---------- Quản lý từ xa ----------
            ["Trigger.Remote"] = "Từ xa",
            ["Settings.RemoteCard"] = "Quản lý từ xa",
            ["Settings.HubUrl"] = "Địa chỉ hub",
            ["Settings.HubToken"] = "Mã agent (token)",
            ["Settings.HubHint"] = "Cowork tự nối ra hub khi khởi động và giữ kết nối. Trạng thái các app của máy này hiện trên web, và từ web bấm được Chạy / Dừng / Khởi động lại. Để trống địa chỉ để tắt.",
            ["Settings.HubReconnect"] = "Kết nối lại",
            ["Settings.HubStatus"] = "Trạng thái:",
            ["HubLink.Disabled"] = "Không dùng",
            ["HubLink.Connecting"] = "Đang kết nối…",
            ["HubLink.Connected"] = "Đã kết nối",
            ["HubLink.Reconnecting"] = "Mất kết nối, đang thử lại…",
            ["HubLink.Failed"] = "Không kết nối được: {0}",
            ["Msg.RemoteRun"] = "Lệnh từ web: chạy “{0}”.",
            ["Msg.RemoteStop"] = "Lệnh từ web: dừng “{0}”.",
            ["Msg.RemoteRestart"] = "Lệnh từ web: khởi động lại “{0}”.",
            ["Msg.RemoteUnknownApp"] = "Không có app nào mang mã này trên máy.",
            ["Msg.RemoteDone"] = "Đã thực hiện.",
            ["Web.SwitchLanguage"] = "English",
            ["Web.Login"] = "Đăng nhập",
            ["Web.Password"] = "Mật khẩu",
            ["Web.LoginFailed"] = "Sai mật khẩu.",
            ["Web.Logout"] = "Đăng xuất",
            ["Web.Machines"] = "Máy",
            ["Web.Online"] = "Trực tuyến",
            ["Web.NeverConnected"] = "Chưa từng kết nối",
            ["Web.LastSeen"] = "Ngoại tuyến · lần cuối thấy {0}",
            ["Web.NoApps"] = "Máy này chưa có app nào.",
            ["Web.ColApp"] = "App",
            ["Web.ColState"] = "Trạng thái",
            ["Web.ColLastRun"] = "Chạy lần cuối",
            ["Web.ColNextRun"] = "Kế tiếp",
            ["Web.Run"] = "Chạy",
            ["Web.Stop"] = "Dừng",
            ["Web.Restart"] = "Khởi động lại",
            ["Web.KeepAliveBadge"] = "giữ chạy",
            ["Web.DisabledBadge"] = "tắt",
            ["Web.Sent"] = "“{0}”: {1}",
            ["Web.AgentRefused"] = "“{0}” không thực hiện được: {1}",
            ["Web.MachineOffline"] = "Máy đang ngoại tuyến.",
            ["Web.MachineUnknown"] = "Không biết máy này.",
            ["Web.Timeout"] = "Máy không phản hồi.",
            ["Web.CommandFailed"] = "Không gửi được lệnh: {0}",
            ["WebState.Idle"] = "Nghỉ",
            ["WebState.Starting"] = "Đang khởi động",
            ["WebState.Running"] = "Đang chạy",
            ["WebState.Stopping"] = "Đang dừng",
            ["WebState.Failed"] = "Lỗi",
            ["WebState.WaitingRestart"] = "Chờ khởi động lại",
        };
}
